cmake_minimum_required(VERSION 3.20)
project(log_compare LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(SPDLOG_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_EXAMPLE OFF CACHE BOOL "" FORCE)
add_subdirectory(${MLOG_SOURCE_DIR} mlog)
add_subdirectory(${SPDLOG_SOURCE_DIR} spdlog)
add_executable(log_compare compare.cpp)
target_link_libraries(log_compare PRIVATE mlog_core spdlog::spdlog)
